name: CI

on:
  push:
    branches: [main, staging, trying]

jobs:
  test-scripts:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install linters
        run: sudo apt-get install -y shellcheck

      - name: lint
        run: make lint

      - name: test
        run: make test

  build-images:
    needs: test-scripts
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image: [rpi-basic, rpi-firewall, k0s-worker]

    steps:
      - uses: actions/checkout@v2

      - name: build ${{ matrix.image }}
        run: make ${{ matrix.image }}

      - name: list-images-content
        run: make list-images-content
